export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCES = 'FETCH_QUIZES_SUCCES';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export const NEXT_ANSWER_STATE = 'NEXT_ANSWER_STATE';
export const IS_FINISHED_QUIZ = 'IS_FINISHED_QUIZ';
export const NEXT_QUIZ_SET = 'NEXT_QUIZ_SET';

export const UPDATE_SET_STATE = 'UPDATE_SET_STATE';
export const GET_QUIZ_COMPONENT = 'GET_QUIZ_COMPONENT';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';